### ISSUE TITLE
ModuleNotFoundError: No module named 'LLM'

### ISSUE THREAD

**Issue by zhongerqiandan** [aiwaves-cn/agents#147]
`
>>> from agents import SOP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../anaconda3/envs/agents/lib/python3.9/site-packages/agents/__init__.py", line 2, in <module>
    from .SOP import *
  File "/Users/.../anaconda3/envs/agents/lib/python3.9/site-packages/agents/SOP.py", line 18, in <module>
    from LLM.base_LLM import *
ModuleNotFoundError: No module named 'LLM'
`

**Comment by jianghuyihei** [comment]
Re pip install ai agents to version 0.0.51
