### ISSUE TITLE
ModuleNotFoundError: No module named 'openai.error'

### ISSUE THREAD

**Issue by zz203** [aiwaves-cn/agents#168]
when I run "python run.py --agent Single_Agent/chat_bot/config.json":
```
（py310) PS D:\other\...\test\agents-master\agents-master\examples> python run.py --agent Single_Agent/chat_bot/config.json      
Traceback (most recent call last):
  File "D:\other\...\test\agents-master\agents-master\examples\run.py", line 3, in <module>
    from agents.SOP import SOP
  File "D:\other\...\test\py310\lib\site-packages\agents\__init__.py", line 2, in <module>
    from .SOP import *
  File "D:\other\...\test\py310\lib\site-packages\agents\SOP.py", line 18, in <module>
    from .LLM.base_LLM import *
  File "D:\other\...\test\py310\lib\site-packages\agents\LLM\base_LLM.py", line 2, in <module>
    import litellm
  File "D:\other\...\test\py310\lib\site-packages\litellm\__init__.py", line 332, in <module>
    from .timeout import timeout
  File "D:\other\...\test\py310\lib\site-packages\litellm\timeout.py", line 20, in <module>
    from openai.error import Timeout
ModuleNotFoundError: No module named 'openai.error'
(py310) PS D:\other\...\test\agents-master\agents-master\examples> 

```
I’ve already got the newest versions of openai and ai_agents:
```
(py310) PS D:\other\...\test\agents-master\agents-master\examples> pip show openai
Name: openai
Version: 1.2.3
Summary: The official Python library for the openai API
Home-page:
Author:
Author-email: OpenAI <support@openai.com>
License:
Location: d:\other\...\test\py310\lib\site-packages
Requires: anyio, distro, httpx, pydantic, tqdm, typing-extensions
Required-by: ai-agents, litellm
(py310) PS D:\other\...\test\agents-master\agents-master\examples> pip show ai_agents
Name: ai-agents
Version: 0.0.52
Summary: An Open-source Framework for Autonomous Language Agents
Home-page: https://github.com/aiwaves-cn/agents
Author: AIWaves
Author-email: contact@aiwaves.cn
License: Apache License 2.0
Location: d:\other\...\test\py310\lib\site-packages
Requires: beautifulsoup4, fastapi, google-api-python-client, google-auth-oauthlib, google-search-results, gradio, langchain, litellm, numpy, openai, pandas, Pillow, protobuf, psutil, pydantic, PyYAML, Requests, selenium, sentence-transformers, serpapi, setuptools, text2vec, torch, tqdm, typing-extensions, uvicorn
Required-by:
(py310) PS D:\other\...\test\agents-master\agents-master\examples> 
```

**Comment by callanwu** [comment]
could the problem be litellm related？ you can check your litellm version and pip the latest version of litellm.

**Comment by callanwu** [comment]
https://github.com/BerriAI/litellm/issues/774 may be helpful for you.

**Comment by ishaan-jaff** [comment]
Hi @callanwu @zz203 apologies for this - we're working on it and should have this resolved in the next 24 hours

**Comment by zz203** [comment]
thanks, I'll wait and see whether my problem can be fixed. by the way, may I join the WeChat group? the picture is out of date. @callanwu
