### ISSUE TITLE
Encountering connection error when running examples

### ISSUE THREAD

**Issue by litsh** [aiwaves-cn/agents#170]
When I run the single agent example using:
```
python run.py --agent Single_Agent/chat_bot/config.json
```
I got connection error:
```
Yang bufan(Yang bufan):hello,What are you looking for me for?
who are you?
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f2b06263640>, 'Connection to api.openai.com timed out. (connect timeout=600)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2b06263640>, 'Connection to api.openai.com timed out. (connect timeout=600)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
  File "/root/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2b06263640>, 'Connection to api.openai.com timed out. (connect timeout=600)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/remote-home/tsli/MultiAgents/agents/examples/run.py", line 41, in <module>
    run(agents,sop,environment)
  File "/remote-home/tsli/MultiAgents/agents/examples/run.py", line 33, in run
    environment.update_memory(memory,current_state)
  File "/remote-home/tsli/MultiAgents/agents/src/agents/Environment/base_environment.py", line 93, in update_memory
    current_embedding = get_embedding(memory.content)
  File "/remote-home/tsli/MultiAgents/agents/src/agents/utils.py", line 68, in get_embedding
    embed = embedding_model.create(model=embed_model_name, input=sentence)
  File "/root/anaconda3/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/root/anaconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 288, in request
    result = self.request_raw(
  File "/root/anaconda3/lib/python3.10/site-packages/openai/api_requestor.py", line 607, in request_raw
    raise error.Timeout("Request timed out: {}".format(e)) from e
openai.error.Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2b06263640>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
```

But I have confirmed that I can access "api.openai.com" using:
```
curl api.openai.com
```
which gives
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meow, I am a Teapot</title>
</head>
<body>
<h1>Sorry, there's nothing but a cat in a teapot here.</h1>
    <img src="https://teapot-cat.pages.dev/teapot.png" alt="Cat in a teapot">
</body>
</html>
```

**Comment by litsh** [comment]
And I can also access openai API via "openai.ChatCompletion.create()".

**Comment by callanwu** [comment]
weird, could you double-check if your api_key is valid and working for the embeddings API, you can follow the steps outlined in the OpenAI documentation: [embeddings API Guide](https://platform.openai.com/docs/guides/embeddings/what-are-embeddings).

> And I can also access openai API via "openai.ChatCompletion.create()".

**Comment by litsh** [comment]
> weird, could you double-check if your api_key is valid and working for the embeddings API, you can follow the steps outlined in the OpenAI documentation: [embeddings API Guide](https://platform.openai.com/docs/guides/embeddings/what-are-embeddings).
> 
> > And I can also access openai API via "openai.ChatCompletion.create()".

Could you please tell me whcih openai version should I use?

**Comment by callanwu** [comment]
Hi @litsh , we have fixed it.(https://github.com/aiwaves-cn/agents/commit/effa456bfa3091ea34e4b396c614e85904b88b8e) And you need to pip the latest version of openai and litellm.
