### ISSUE TITLE
not JSON serializable error when running multi agent examples

### ISSUE THREAD

**Issue by srcJin** [aiwaves-cn/agents#177]
Hi! When I was running the multi-agent examples locally, it gave me an error after the first sentence. However, the single agent cases works.

TypeError: Object of type ModelResponse is not JSON serializable

Full terminal output: (I also printed the chat_messages)
```
(agents) D:\github\agents_forked\examples>python run.py --agent Multi_Agent/software_company/config.json 
Alice(Boss):Please write code for the target game
chat_messages= [{'role': 'user', 'content': 'None;\n Here is the The chat history:\n {name:Alice\n role: Boss \n speak content : Please write code for the target game; };\nHere is the last query 
you especially need to pay attention:\nname:Alice\n role: Boss \n speak content : Please write code for the target game; ;\n Here is the relevant conversation: \n{} \n\n'}]
Traceback (most recent call last):
  File "D:\github\agents_forked\examples\run.py", line 41, in <module>
    run(agents,sop,environment)
  File "D:\github\agents_forked\examples\run.py", line 24, in run
    current_state,current_agent= sop.next(environment,agents)
  File "d:\github\agents_forked\src\agents\SOP.py", line 271, in next
    next_state = self.transit(
  File "d:\github\agents_forked\src\agents\SOP.py", line 130, in transit
    response = self.LLM.get_response(
  File "d:\github\agents_forked\src\agents\LLM\base_LLM.py", line 125, in get_response
    save_logs(self.log_path, messages, response)
  File "d:\github\agents_forked\src\agents\utils.py", line 162, in save_logs
    json.dump(log, f, ensure_ascii=False, indent=2)
  File "C:\Users\gao-j\anaconda3\envs\agents\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\gao-j\anaconda3\envs\agents\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\gao-j\anaconda3\envs\agents\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\gao-j\anaconda3\envs\agents\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\gao-j\anaconda3\envs\agents\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ModelResponse is not JSON serializable

```

**Comment by callanwu** [comment]
Hi @srcJin ,
we fixed it in https://github.com/aiwaves-cn/agents/pull/178/commits/e300c0b59f7b6924eae423e4863d4f166e14f0db. Thanks for pointing this out:)
