### ISSUE TITLE
openai.Embedding error

### ISSUE THREAD

**Issue by iFreeshine** [aiwaves-cn/agents#181]
to test examples : python Single_Agent/run_gradio.py --agent Single_Agent/chat_bot/config.json   

Yang bufan(Yang bufan):hello,What are you looking for me for?
Traceback (most recent call last):
  File "E:\my python\agents\examples\Single_Agent\gradio_backend.py", line 112, in <module>
    run(agents,sop,environment)
  File "E:\my python\agents\examples\Single_Agent\gradio_backend.py", line 87, in run
    environment.update_memory(memory,current_state)
  File "D:\Python\Lib\site-packages\agents\Environment\base_environment.py", line 93, in update_memory
    current_embedding = get_embedding(memory.content)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\agents\utils.py", line 68, in get_embedding
    embed = embedding_model.create(model=embed_model_name, input=sentence)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\openai\_utils\_proxy.py", line 22, in __getattr__
    return getattr(self.__get_proxied__(), attr)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\openai\_utils\_proxy.py", line 43, in __get_proxied__
    return self.__load__()
           ^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\openai\lib\_old_api.py", line 33, in __load__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1:

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

**Comment by callanwu** [comment]
We have fixed it(https://github.com/aiwaves-cn/agents/commit/f4db88093846bb17160c0448b91a6ac11ded8a4e). Use our latest codebase:)
