### ISSUE TITLE
How to run it? :)

### ISSUE THREAD

**Issue by simjak** [aiwaves-cn/agents#202]
python3.11 examples/software_dev/run_train.py

```
global_logger_for_training - INFO - Logs are saved inexamples/software_dev/logs/2024-07-01_10-27-11
wandb: Currently logged in as: simjak (simjak-Aurelio AI). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.17.3 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.16.6
wandb: Run data is saved locally in /Users/jakit/simonas/open-source/agents/wandb/run-20240701_102712-9vs5z39t
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run exalted-waterfall-2
wandb: ⭐️ View project at https://wandb.ai/simjak-Aurelio%20AI/agents-examples_software_dev
wandb: 🚀 View run at https://wandb.ai/simjak-Aurelio%20AI/agents-examples_software_dev/runs/9vs5z39t
global_logger_for_training - INFO - has_ground_truth: False, has_eval_score: False
global_logger_for_training - INFO - meta_loss["order"]: ['part1_no_gt_no_score', 'task_description', 'model_output', 'note_output_score']
Traceback (most recent call last):
  File "/Users/jakit/simonas/open-source/agents/examples/software_dev/run_train.py", line 19, in <module>
    trainer.train()
  File "/Users/jakit/simonas/open-source/agents/src/agents/optimization/trainer.py", line 248, in train
    solution = Solution(config=SolutionConfig(self.initial_solution_path))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jakit/simonas/open-source/agents/src/agents/task/solution.py", line 75, in __init__
    self.sop.init_node_prompts()
  File "/Users/jakit/simonas/open-source/agents/src/agents/task/sop.py", line 196, in init_node_prompts
    node.node_prompts = node.load_node_prompts()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jakit/simonas/open-source/agents/src/agents/task/node.py", line 393, in load_node_prompts
    node_prompts[agent_name][prompt_type] = Node.apply_var_to_prompt(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jakit/simonas/open-source/agents/src/agents/task/node.py", line 426, in apply_var_to_prompt
    raise ValueError(
ValueError: Invalid prompt type 'task', the supported prompt types are dict_keys(['target']).
wandb: 🚀 View run exalted-waterfall-2 at: https://wandb.ai/simjak-Aurelio%20AI/agents-examples_software_dev/runs/9vs5z39t
wandb: ⭐️ View project at: https://wandb.ai/simjak-Aurelio%20AI/agents-examples_software_dev
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240701_102712-9vs5z39t/logs

```

**Comment by zdondada** [comment]
I integrated the concept with CrewAI to make it easier to run

**Comment by MichaelZhouwang** [comment]
> I integrated the concept with CrewAI to make it easier to run

That would be super cool! Could you share your implementations? That would be super nice!

**Comment by zdondada** [comment]
Sure, I wanted to work out this last wrinkle first. I've set it up to
generate SQLite database but after adding authentication it's being a
bugger so I just gotta fix the auth

**Comment by PoooWeeeHiii** [comment]
描述根因和修复，给出运行命令 PYTHONPATH=src python examples/software_dev/run_train.py，注明需有效 API Key/Azure 配置。
