### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by locals2-j** [aiwaves-cn/agents#33]
Great paper all though running with Gradio and on Terminal gives this error using the example configs. Have not tested with FastAPI yet.

C:\Users\bosef\agents\examples>python run.py --agent Single_Agent/customer_service/customer_websearch.json
Traceback (most recent call last):
  File "C:\Users\bosef\agents\examples\run.py", line 43, in <module>
    agents,sop,environment = init(args.agent)
  File "C:\Users\bosef\agents\examples\run.py", line 13, in init
    sop = SOP.from_config(config)
  File "C:\Users\bosef\AppData\Local\Programs\Python\Python310\lib\site-packages\agents\SOP.py", line 72, in from_config
    sop = SOP(**config)
  File "C:\Users\bosef\AppData\Local\Programs\Python\Python310\lib\site-packages\agents\SOP.py", line 44, in __init__
    self.init_states(kwargs["states"])
  File "C:\Users\bosef\AppData\Local\Programs\Python\Python310\lib\site-packages\agents\SOP.py", line 78, in init_states
    self.states[state_name] = State(**state_dict)
  File "C:\Users\bosef\AppData\Local\Programs\Python\Python310\lib\site-packages\agents\State.py", line 31, in __init__
    self.init_components(kwargs["agent_states"])
  File "C:\Users\bosef\AppData\Local\Programs\Python\Python310\lib\site-packages\agents\State.py", line 123, in init_components
    component_dict["WebSearchComponent"] = WebSearchComponent(
  File "C:\Users\bosef\AppData\Local\Programs\Python\Python310\lib\site-packages\agents\Component\ToolComponent.py", line 183, in __init__
    assert engine_name in WebSearchComponent.__ENGINE_NAME__
AssertionError

**Comment by locals2-j** [comment]
Fixed. API key issue.
