### ISSUE TITLE
Getting Connection error while running in Local

### ISSUE THREAD

**Issue by purvaja2001** [aiwaves-cn/agents#73]
While running the code, I am getting this error

openai.error.APIConnectionError: Error communicating with OpenAI: Please check proxy URL. It is malformed and could be missing the host.

Also what to be given in API_Base and proxy in Config file?

**Comment by jianghuyihei** [comment]
If you need a proxy or API_ Base, then you need to set the keyword "PROXY" in config (it always be“ http://127.0.0.1: {port} "),  keyword" API_ BASE "(it always be" https://*****/v1 "), generally speaking, only one needs to be filled in for proxy and api_base

**Comment by jianghuyihei** [comment]
> While running the code, I am getting this error
> 
> openai.error.APIConnectionError: Error communicating with OpenAI: Please check proxy URL. It is malformed and could be missing the host.
> 
> Also what to be given in API_Base and proxy in Config file?

If you need a proxy or API_ Base, then you need to set the keyword "PROXY" in config (it always be“ http://127.0.0.1/: {port} "), keyword" API_ BASE "(it always be" https://*****/v1 "), generally speaking, only one needs to be filled in for proxy and api_base

**Comment by callanwu** [comment]
if you don't need to use a proxy or API_ Base, you can remove these from config.

**Comment by purvaja2001** [comment]
Yeah! Okay Got it
And one more doubt, does the code support any other models apart from openai?

**Comment by purvaja2001** [comment]
And if I remove both Proxy and API_base 
I am getting
AssertionError : PROXY error, PROXY must be http or socks

**Comment by callanwu** [comment]
you can pull our latest repo. we have fixed it！ thx :)

**Comment by callanwu** [comment]
https://github.com/aiwaves-cn/agents/blob/b19219b850bc3de26d4b66dc26e5f228f830923a/src/agents/LLM/base_LLM.py#L54C1-L54C1
you can check here.

**Comment by purvaja2001** [comment]
I got this err
TypeError issubclass() arg 1 must be a class

**Comment by callanwu** [comment]
could your provide detailed error messages?

**Comment by purvaja2001** [comment]
2023-09-21 13:06:49.113280: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-09-21 13:06:49.113608: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:\Users\Purvaja Ammanabrolu\Desktop\agents\examples\run.py", line 6, in <module>
    from SOP import SOP
  File "C:\Users\Purvaja Ammanabrolu\Desktop\agents\examples\../src/agents\SOP.py", line 18, in <module>
    from LLM.base_LLM import *
  File "C:\Users\Purvaja Ammanabrolu\Desktop\agents\examples\../src/agents\LLM\base_LLM.py", line 6, in <module>
    from utils import save_logs
  File "C:\Users\Purvaja Ammanabrolu\Desktop\agents\examples\../src/agents\utils.py", line 28, in <module>
    from langchain.document_loaders import UnstructuredFileLoader
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\tools\__init__.py", line 3, in <module>
    from langchain.tools.arxiv.tool import ArxivQueryRun
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\tools\arxiv\tool.py", line 12, in <module>
    from langchain.utilities.arxiv import ArxivAPIWrapper
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\utilities\__init__.py", line 3, in <module>
    from langchain.utilities.apify import ApifyWrapper
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\utilities\apify.py", line 5, in <module>
    from langchain.document_loaders import ApifyDatasetLoader
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\document_loaders\__init__.py", line 42, in <module>
    from langchain.document_loaders.embaas import EmbaasBlobLoader, EmbaasLoader
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\document_loaders\embaas.py", line 54, in <module>
    class BaseEmbaasLoader(BaseModel):
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 542, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 804, in pydantic.fields.ModelField.populate_validators
  File "pydantic\validators.py", line 696, in find_validators
  File "pydantic\validators.py", line 585, in pydantic.validators.make_typeddict_validator
  File "pydantic\annotated_types.py", line 35, in pydantic.annotated_types.create_model_from_typeddict
  File "pydantic\main.py", line 988, in pydantic.main.create_model
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1157, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
PS C:\Users\Purvaja Ammanabrolu\Desktop\agents\examples> python run.py --agent Single_Agent/customer_service/customer_knowledge.json
2023-09-21 13:10:32.130584: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-09-21 13:10:32.131405: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:\Users\Purvaja Ammanabrolu\Desktop\agents\examples\run.py", line 6, in <module>
    from SOP import SOP
  File "C:\Users\Purvaja Ammanabrolu\Desktop\agents\examples\../src/agents\SOP.py", line 18, in <module>
    from LLM.base_LLM import *
  File "C:\Users\Purvaja Ammanabrolu\Desktop\agents\examples\../src/agents\LLM\base_LLM.py", line 6, in <module>
    from utils import save_logs
  File "C:\Users\Purvaja Ammanabrolu\Desktop\agents\examples\../src/agents\utils.py", line 28, in <module>
    from langchain.document_loaders import UnstructuredFileLoader
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\tools\__init__.py", line 3, in <module>
    from langchain.tools.arxiv.tool import ArxivQueryRun
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\tools\arxiv\tool.py", line 12, in <module>
    from langchain.utilities.arxiv import ArxivAPIWrapper
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\utilities\__init__.py", line 3, in <module>
    from langchain.utilities.apify import ApifyWrapper
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\utilities\apify.py", line 5, in <module>
    from langchain.document_loaders import ApifyDatasetLoader
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\document_loaders\__init__.py", line 42, in <module>
    from langchain.document_loaders.embaas import EmbaasBlobLoader, EmbaasLoader
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\document_loaders\embaas.py", line 54, in <module>
    class BaseEmbaasLoader(BaseModel):
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 542, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 804, in pydantic.fields.ModelField.populate_validators
  File "pydantic\validators.py", line 696, in find_validators
  File "pydantic\validators.py", line 585, in pydantic.validators.make_typeddict_validator
  File "pydantic\annotated_types.py", line 35, in pydantic.annotated_types.create_model_from_typeddict
  File "pydantic\main.py", line 988, in pydantic.main.create_model
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Purvaja Ammanabrolu\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1157, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by callanwu** [comment]
it looks like a langchain version issue. maybe you can try ```pip install langchain==0.0.231```?

**Comment by purvaja2001** [comment]
This is the same version I am using 
But the issue is persisting

**Comment by purvaja2001** [comment]
This worked Jialong Wu! Thank you 
But that AssertionError still exists
I can see the Mike's (customer service personnel) first message but this assertion error came up Proxy error, Proxy should be http or socks

**Comment by callanwu** [comment]
https://github.com/aiwaves-cn/agents/blob/b19219b850bc3de26d4b66dc26e5f228f830923a/src/agents/LLM/base_LLM.py#L54C1-L54C1
you can change your code locally like this or delete this line 
```assert "http:" in os.environ["PROXY"] or "socks" in os.environ["PROXY"],"PROXY error,PROXY must be http or socks"```
and remove "proxy" in the config

**Comment by purvaja2001** [comment]
I have done that but now getting Connection error

openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000206A9783A60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by callanwu** [comment]
can you directly communicate with openai？ if not， you should set proxy or base_url.

**Comment by purvaja2001** [comment]
Does the code support any other Models other than openai?

**Comment by callanwu** [comment]
sorry, now we only support for models based openai. but you can customize 
https://github.com/aiwaves-cn/agents/blob/master/src/agents/LLM/base_LLM.py
and make sure your customized LLM class have ```get_response()``` or you can set proxy or base_url to use current models based openai.
