### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._six'

### ISSUE THREAD

**Issue by ekiwi111** [aiwaves-cn/agents#93]
1. Cloned and installed with `pip install -e .`
2. Went to examples directory `cd examples`
3. Tried one of the examples with `python Single_Agent/run_gradio.py --agent Single_Agent/shopping_assistant/config.json`

Got the following output
```
server: executing `python Single_Agent/gradio_backend.py --agent Single_Agent/shopping_assistant/config.json` ...
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1130, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/user/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/user/anaconda3/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 42, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/home/user/anaconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 38, in <module>
    from .deepspeed import deepspeed_config, is_deepspeed_zero3_enabled
  File "/home/user/anaconda3/lib/python3.9/site-packages/transformers/deepspeed.py", line 37, in <module>
    from accelerate.utils.deepspeed import HfDeepSpeedConfig as DeepSpeedConfig
  File "/home/user/anaconda3/lib/python3.9/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/user/anaconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/user/anaconda3/lib/python3.9/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/user/anaconda3/lib/python3.9/site-packages/accelerate/utils/__init__.py", line 136, in <module>
    from .launch import (
  File "/home/user/anaconda3/lib/python3.9/site-packages/accelerate/utils/launch.py", line 33, in <module>
    from ..utils.other import is_port_in_use, merge_dicts
  File "/home/user/anaconda3/lib/python3.9/site-packages/accelerate/utils/other.py", line 32, in <module>
    from deepspeed import DeepSpeedEngine
  File "/home/user/anaconda3/lib/python3.9/site-packages/deepspeed/__init__.py", line 14, in <module>
    from . import module_inject
  File "/home/user/anaconda3/lib/python3.9/site-packages/deepspeed/module_inject/__init__.py", line 1, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing
  File "/home/user/anaconda3/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 15, in <module>
    from ..runtime.zero import GatheredParameters
  File "/home/user/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/__init__.py", line 6, in <module>
    from .partition_parameters import ZeroParamType
  File "/home/user/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 22, in <module>
    from .linear import LinearModuleForZeroStage3, zero3_linear_wrap
  File "/home/user/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/linear.py", line 20, in <module>
    from deepspeed.runtime.utils import noop_decorator
  File "/home/user/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/utils.py", line 19, in <module>
    from torch._six import inf
ModuleNotFoundError: No module named 'torch._six'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/Developer/_experiments/agents/examples/Single_Agent/gradio_backend.py", line 7, in <module>
    from agents.SOP import SOP
  File "/home/user/Developer/_experiments/agents/src/agents/__init__.py", line 2, in <module>
    from .SOP import *
  File "/home/user/Developer/_experiments/agents/src/agents/SOP.py", line 18, in <module>
    from LLM.base_LLM import *
  File "/home/user/Developer/_experiments/agents/examples/../src/agents/LLM/base_LLM.py", line 6, in <module>
    from utils import save_logs
  File "/home/user/Developer/_experiments/agents/examples/../src/agents/utils.py", line 25, in <module>
    from text2vec import semantic_search
  File "/home/user/anaconda3/lib/python3.9/site-packages/text2vec/__init__.py", line 8, in <module>
    from text2vec.bertmatching_model import BertMatchModel
  File "/home/user/anaconda3/lib/python3.9/site-packages/text2vec/bertmatching_model.py", line 16, in <module>
    from transformers import BertForSequenceClassification, BertTokenizer
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/user/anaconda3/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1121, in __getattr__
    value = getattr(module, name)
  File "/home/user/anaconda3/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1120, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/user/anaconda3/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1132, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
No module named 'torch._six'
```

Torch version installed:
```
>>> import torch
>>> print(torch. __version__)
2.0.1+cu118
```

**Comment by ekiwi111** [comment]
Solved with:
```
pip uninstall deepspeed
pip install deepspeed
```
